### ISSUE TITLE
Cannot run demo properly in Rails 5

### ISSUE THREAD

**Issue by HansBug** [jrobertson/tagcloudbase#1]
In Rails 5. this gem's demo program cannot run properly.
The error is 'Divided by zero', like this:

➜  workspace git:(master) ✗ cd hg_app                                                                                                                                                                      
➜  hg_app git:(master) ✗ rails console                                                                                                                                                                     
Running via Spring preloader in process 11146                                                                                                                                                              
Loading development environment (Rails 5.0.2)                                                                                                                                                              
irb(main):001:0> all_tags = {Egypt: 45, UK: 103, France: 56, Belgium: 53, Ireland: 49, China: 256, Somalia: 21}.to_a                                                                                       
=> [[:Egypt, 45], [:UK, 103], [:France, 56], [:Belgium, 53], [:Ireland, 49], [:China, 256], [:Somalia, 21]]                                                                                                
irb(main):002:0> puts TagCloudBase.new(all_tags).to_dynarex.to_xml pretty: true                                                                                                                            
ZeroDivisionError: divided by 0                                                                                                                                                                            
        from /home/coding/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tagcloudbase-0.1.4/lib/tagcloudbase.rb:22:in `/'                                                                                  
        from /home/coding/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tagcloudbase-0.1.4/lib/tagcloudbase.rb:22:in `block in initialize'                                                                
        from /home/coding/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tagcloudbase-0.1.4/lib/tagcloudbase.rb:20:in `each'                                                                               
        from /home/coding/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tagcloudbase-0.1.4/lib/tagcloudbase.rb:20:in `initialize'                                                                         
        from (irb):2:in `new'

**Comment by jrobertson** [comment]
Try enclosing each tag cloud value in an Array with an empty string item followed by the value e.g.

    all_tags = {Egypt: ['',45], UK: ['',103], France: ['',56], Belgium: ['',53], Ireland: ['',49], China: ['',256], Somalia: ['',21]}.to_a

I have today updated the gem and the documentation to fix a bug relating to generating a web page from the tag cloud. Thank you for your bringing the issue to my attention.
